api_version = "2026-01"

[[extensions]]
name        = "t:name"
description = "t:description"
handle      = "no-sale-coupon"
type        = "function"

[[extensions.targeting]]
target      = "purchase.order-discount.run"
input_query = "src/run.graphql"
export      = "run"

[extensions.build]
command = "npx esbuild --bundle --outfile=dist/function.js src/run.js"
path    = "dist/function.wasm"
watch   = ["src/**/*.js"]
