api_version = "2026-01"

[[extensions]]
type        = "function"
name        = "No Sale Coupon Stacking"
handle      = "no-sale-coupon"
description = "Bloqueia cupões quando o carrinho contém produtos já em promoção"

[[extensions.targeting]]
target      = "purchase.order-discount.run"
input_query = "src/run.graphql"
export      = "run"
